[package]
name = "contest-notifier"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }